### Site
title: Sagen.io
url: https://sagen.io
baseurl:
tagline: "PLACEHOLDER #1"
description: |
  "PLACEHOLDER #2"
author:
  name: Andreas Sagen
  url: https://twitter.com/andreas_sagen
  email: developer@sagen.io

### Paginate
paginate: 10

### Sitemap


### Metadata
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

include:
  - "_pages"

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "scripts",
    ".*"
  ]
