### Site
title: Sagen.io
url: http://exterex.github.io
baseurl: "/sagen.io"
tagline: "PLACEHOLDER #1"
description: |
  "PLACEHOLDER #2"
author:
  name: Andreas Sagen
  url: https://twitter.com/andreas_sagen
  email: developer@sagen.io

### Paginate
paginate: 10

### Sitemap


### Metadata
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

include:
  - "_pages"

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
    "LICENSE",
    "license",
    ".gitignore",
    ".gitattributes",
    "Makefile",
    ".devcontainer/",
    ".vscode/",
    ".editorconfig",
    "robots.txt",
    "Dockerfile",
    "docker-compose.test.yml",
    ".github/",
    ".dockerignore",
  ]
